### PR TITLE
Arithmetic issues and metronome clicks

### PR DESCRIPTION
**Pull request by paulfd**
Hi !

I did some tweaks to avoid #2 and changed the metronome sound to smoother one (Ardour meters did not like it much for example, as it had a very strong high frequency content). The metronome is not perfect but probably good enough for the purpose. I was wondering if it made sense to have it on a separate output maybe?

### CODE REVIEW

**Comment by devcurmudgeon** [comment]
Hi and thanks very much for this contribution - I appreciate the cleanups and this metronome does sound better. Just a couple of things:

- my idea for the click was to have it only during the recording of the first loop, to make it easier to get that first loop in sync when starting a new session/song

- 9cd9bbddb55592b0719301a4fd8ccd64defb8a13 doesn't seem to compile for me: I get alo.c:619:52: error: invalid conversion from 'float*' to 'uint32_t {aka unsigned int}' [-fpermissive]
    click(self, self->ports.output, 0, sample_offset);

**Comment by paulfd** [comment]
> Hi and thanks very much for this contribution - I appreciate the cleanups and this metronome does sound better. Just a couple of things:
> 
>     * my idea for the click was to have it only during the recording of the first loop, to make it easier to get that first loop in sync when starting a new session/song

OK so if you have any loop in store then no click should be heard? Or if we're recording a solo loop (no other active loops)?

>     * [9cd9bbd](https://github.com/devcurmudgeon/alo/commit/9cd9bbddb55592b0719301a4fd8ccd64defb8a13) doesn't seem to compile for me: I get alo.c:619:52: error: invalid conversion from 'float*' to 'uint32_t {aka unsigned int}' [-fpermissive]
>       click(self, self->ports.output, 0, sample_offset);

Yes I messed up this commit apparently there is a mismatch between the function prototype and the calls in run().
I can rebase the tree if you want to keep the history compiling.

I wonder if I messed up something in the timing code since I can't seem to have it properly sync to a full bar at the moment.

**Comment by devcurmudgeon** [comment]
> OK so if you have any loop in store then no click should be heard? Or if we're recording a solo loop (no other active loops)?

Yes - the click should stop as soon as any loop finishes recording - see https://github.com/devcurmudgeon/alo/blob/master/source/alo.c#L527 (seems I messed up indentation there)

**Comment by paulfd** [comment]
So should the click also only apply for when the loop is armed?

**Comment by devcurmudgeon** [comment]
Sorry for the delay. Ideally yes the click would only happen when loop is armed, but what you've done is already a clear improvement so I'm merging it. Thanks again!

**Pull request merged**
